# rollback change
---
-
  hosts: localhost
  name: "rollback change with Ansible"
  tasks:
    -
      name: "rollback a change with Ansible task(s)"
      uri:
        url: "http://35.186.151.37/carts/1/items/promotion/0"
    -
      name: "send Dynatrace custom configuration event with business context information"
      uri:
        url: https://dwy90787.live.dynatrace.com/api/v1/problem/details/{{ ProblemID }}/comments?Api-Token=dt0c01.HLULYHXSP3LD7MQJAVT45J2M.SFSTIFAZYKBR3B7SENEWIWOECPKHNVCKZHUTHIWJECGQZLN2BHQEH2273QNVIYQN
        method: POST
        headers:
          content-type: application/json
        body:
          comment: "Rolling back promotion campaign"
          user: Admin
          context: Ansible
        body_format: json
        status_code: 200
