- name: Restart a Service
  hosts: all
  tasks:
    - name: Restart service crond, in all case
      ansible.builtin.service:
        name: crond
        state: restarted
      become: yes
      become_method: su
      become_user: nobody
      become_flags: '-s /bin/sh'
